# Generated by Django 4.2.2 on 2023-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syndrome',
            name='code_envoie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='code_r',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='syndrome',
            field=models.CharField(max_length=20),
        ),
    ]
