# Generated by Django 4.2.2 on 2023-06-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_syndrome_code_envoie_alter_syndrome_code_r_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syndrome',
            name='code_envoie',
        ),
        migrations.RemoveField(
            model_name='syndrome',
            name='code_r',
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='code_envoyé',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='code_reçu',
            field=models.CharField(max_length=20),
        ),
    ]
