# Generated by Django 4.2.2 on 2023-06-20 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_syndrome_code_envoie_remove_syndrome_code_r_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syndrome',
            name='syndrome',
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='code_envoyé',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[01]*$', 'Entrez des 0 et des 1 uniquement.')]),
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='code_reçu',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[01]*$', 'Entrez des 0 et des 1 uniquement.')]),
        ),
    ]
