# Generated by Django 4.2.2 on 2023-06-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_syndrome_syndrome_alter_syndrome_code_envoyé_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syndrome',
            name='sum_field',
            field=models.IntegerField(editable=False),
        ),
    ]
