# Generated by Django 4.2.2 on 2023-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_syndrome_sum_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syndrome',
            name='sum_field',
        ),
        migrations.AlterField(
            model_name='syndrome',
            name='valeur_syndrome',
            field=models.IntegerField(editable=False),
        ),
    ]
