# Generated by Django 4.2.2 on 2023-06-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_syndrome_sum_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syndrome',
            name='état',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
