# Generated by Django 4.2.2 on 2023-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_syndrome_état'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syndrome',
            name='état',
            field=models.TextField(editable=False, max_length=20),
        ),
    ]
