# Generated by Django 4.2.4 on 2023-08-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_pubkey_syndrome_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='syndrome',
            name='fonction_goppa',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
