# Generated by Django 4.2.4 on 2023-08-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_delete_pubkey_remove_syndrome_fonction_goppa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='syndrome',
            name='fgoppa',
        ),
        migrations.RemoveField(
            model_name='syndrome',
            name='n',
        ),
    ]
